package com.nnti.Privilege.model.bean;

import java.util.Date;

public class ActivityConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.id
     *
     * @mbggenerated
     */
    private String englishtitle;

    public String getEnglishtitle() {
        return englishtitle;
    }

    public void setEnglishtitle(String englishtitle) {
        this.englishtitle = englishtitle;
    }

    private Integer id;

    private int sidcount;
    public int getSidcount() {
        return sidcount;
    }

    public void setSidcount(int sidcount) {
        this.sidcount = sidcount;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.amount
     *
     * @mbggenerated
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.scope
     *
     * @mbggenerated
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.times
     *
     * @mbggenerated
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.entrance
     *
     * @mbggenerated
     */
    private String entrance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.deposit
     *
     * @mbggenerated
     */
    private Double deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.bet
     *
     * @mbggenerated
     */
    private Double bet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.multiple
     *
     * @mbggenerated
     */
    private Integer multiple;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.multiplestatus
     *
     * @mbggenerated
     */
    private Integer multiplestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.platform
     *
     * @mbggenerated
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.depositStartTime
     *
     * @mbggenerated
     */
    private Date depositstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.depositEndTime
     *
     * @mbggenerated
     */
    private Date depositendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.activityStartTime
     *
     * @mbggenerated
     */
    private Date activitystarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.activityEndTime
     *
     * @mbggenerated
     */
    private Date activityendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.betStartTime
     *
     * @mbggenerated
     */
    private Date betstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.betEndTime
     *
     * @mbggenerated
     */
    private Date betendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.machineCode
     *
     * @mbggenerated
     */
    private Integer machinecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_config.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.id
     *
     * @return the value of activity_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.id
     *
     * @param id the value for activity_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.title
     *
     * @return the value of activity_config.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.title
     *
     * @param title the value for activity_config.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.amount
     *
     * @return the value of activity_config.amount
     *
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.amount
     *
     * @param amount the value for activity_config.amount
     *
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.level
     *
     * @return the value of activity_config.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.level
     *
     * @param level the value for activity_config.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.createTime
     *
     * @return the value of activity_config.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.createTime
     *
     * @param createtime the value for activity_config.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.updateTime
     *
     * @return the value of activity_config.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.updateTime
     *
     * @param updatetime the value for activity_config.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.scope
     *
     * @return the value of activity_config.scope
     *
     * @mbggenerated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.scope
     *
     * @param scope the value for activity_config.scope
     *
     * @mbggenerated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.times
     *
     * @return the value of activity_config.times
     *
     * @mbggenerated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.times
     *
     * @param times the value for activity_config.times
     *
     * @mbggenerated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.entrance
     *
     * @return the value of activity_config.entrance
     *
     * @mbggenerated
     */
    public String getEntrance() {
        return entrance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.entrance
     *
     * @param entrance the value for activity_config.entrance
     *
     * @mbggenerated
     */
    public void setEntrance(String entrance) {
        this.entrance = entrance == null ? null : entrance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.status
     *
     * @return the value of activity_config.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.status
     *
     * @param status the value for activity_config.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.deposit
     *
     * @return the value of activity_config.deposit
     *
     * @mbggenerated
     */
    public Double getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.deposit
     *
     * @param deposit the value for activity_config.deposit
     *
     * @mbggenerated
     */
    public void setDeposit(Double deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.bet
     *
     * @return the value of activity_config.bet
     *
     * @mbggenerated
     */
    public Double getBet() {
        return bet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.bet
     *
     * @param bet the value for activity_config.bet
     *
     * @mbggenerated
     */
    public void setBet(Double bet) {
        this.bet = bet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.multiple
     *
     * @return the value of activity_config.multiple
     *
     * @mbggenerated
     */
    public Integer getMultiple() {
        return multiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.multiple
     *
     * @param multiple the value for activity_config.multiple
     *
     * @mbggenerated
     */
    public void setMultiple(Integer multiple) {
        this.multiple = multiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.multiplestatus
     *
     * @return the value of activity_config.multiplestatus
     *
     * @mbggenerated
     */
    public Integer getMultiplestatus() {
        return multiplestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.multiplestatus
     *
     * @param multiplestatus the value for activity_config.multiplestatus
     *
     * @mbggenerated
     */
    public void setMultiplestatus(Integer multiplestatus) {
        this.multiplestatus = multiplestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.platform
     *
     * @return the value of activity_config.platform
     *
     * @mbggenerated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.platform
     *
     * @param platform the value for activity_config.platform
     *
     * @mbggenerated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.depositStartTime
     *
     * @return the value of activity_config.depositStartTime
     *
     * @mbggenerated
     */
    public Date getDepositstarttime() {
        return depositstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.depositStartTime
     *
     * @param depositstarttime the value for activity_config.depositStartTime
     *
     * @mbggenerated
     */
    public void setDepositstarttime(Date depositstarttime) {
        this.depositstarttime = depositstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.depositEndTime
     *
     * @return the value of activity_config.depositEndTime
     *
     * @mbggenerated
     */
    public Date getDepositendtime() {
        return depositendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.depositEndTime
     *
     * @param depositendtime the value for activity_config.depositEndTime
     *
     * @mbggenerated
     */
    public void setDepositendtime(Date depositendtime) {
        this.depositendtime = depositendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.activityStartTime
     *
     * @return the value of activity_config.activityStartTime
     *
     * @mbggenerated
     */
    public Date getActivitystarttime() {
        return activitystarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.activityStartTime
     *
     * @param activitystarttime the value for activity_config.activityStartTime
     *
     * @mbggenerated
     */
    public void setActivitystarttime(Date activitystarttime) {
        this.activitystarttime = activitystarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.activityEndTime
     *
     * @return the value of activity_config.activityEndTime
     *
     * @mbggenerated
     */
    public Date getActivityendtime() {
        return activityendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.activityEndTime
     *
     * @param activityendtime the value for activity_config.activityEndTime
     *
     * @mbggenerated
     */
    public void setActivityendtime(Date activityendtime) {
        this.activityendtime = activityendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.betStartTime
     *
     * @return the value of activity_config.betStartTime
     *
     * @mbggenerated
     */
    public Date getBetstarttime() {
        return betstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.betStartTime
     *
     * @param betstarttime the value for activity_config.betStartTime
     *
     * @mbggenerated
     */
    public void setBetstarttime(Date betstarttime) {
        this.betstarttime = betstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.betEndTime
     *
     * @return the value of activity_config.betEndTime
     *
     * @mbggenerated
     */
    public Date getBetendtime() {
        return betendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.betEndTime
     *
     * @param betendtime the value for activity_config.betEndTime
     *
     * @mbggenerated
     */
    public void setBetendtime(Date betendtime) {
        this.betendtime = betendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.machineCode
     *
     * @return the value of activity_config.machineCode
     *
     * @mbggenerated
     */
    public Integer getMachinecode() {
        return machinecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.machineCode
     *
     * @param machinecode the value for activity_config.machineCode
     *
     * @mbggenerated
     */
    public void setMachinecode(Integer machinecode) {
        this.machinecode = machinecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_config.remark
     *
     * @return the value of activity_config.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_config.remark
     *
     * @param remark the value for activity_config.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}