package com.nnti.Privilege.dao.master;

import com.nnti.Privilege.model.bean.ActivityConfig;
import com.nnti.Privilege.model.bean.ActivityConfigExample;
import com.nnti.Privilege.model.vo.Prize;

import java.sql.Timestamp;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ActivityConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    int countByExample(ActivityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    int deleteByExample(ActivityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    int insert(ActivityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    int insertSelective(ActivityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    List<ActivityConfig> selectByExample(ActivityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    ActivityConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActivityConfig record, @Param("example") ActivityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActivityConfig record, @Param("example") ActivityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityConfig record);

    List<ActivityConfig> getList(@Param("title") String title, @Param("entrance") String entrance, @Param("level") String level );
    
    List<ActivityConfig>  getCheckVipFeeList(@Param("title") String title, @Param("entrance") String entrance, @Param("level") String level,       @Param("startTime") Timestamp startTime,  @Param("endTime") Timestamp endTime ); 
    
    List getListBySql(Map<String, Object> params);
    
    Double  getbankDepositBySql(Map<String, Object> params);
    
    Double  thirdPaymentDepositBySql(Map<String, Object> params);
    
    void savePrize(Prize prize);
    
    int updatePrivileges(Map<String, Object> params);
    
    int updateUserCreditSql(Map<String, Object> params);
    
    int insertCreditLog(  Map<String, Object> params);
    
    int  insertActivityConfig(  Map<String, Object> params);
    
    int  insertProposal(  Map<String, Object> params);
    
    
}