package dfh.model.enums;

public enum CreditChangeType
{
	  NETPAY("NETPAY", "在线支付"),
	VIP_FREE_MONTH("VIPFREE", "VIP每月免费筹码"),

	REPAIR_PAYORDER("REPAIR_PAYORDER", "支付补单"),
	  CASHIN("CASHIN", "存款"), 
	  CASHOUT("CASHOUT", "提款"),
	  CASHOUT_RETURN("CASHOUT_RETURN", "退还提款"),
	  REBANKINFO("REBANKINFO", "银改"),
	  PRIZE("PRIZE", "幸运抽奖"),
	LEVELPRIZE("LEVELPRIZE", "晋级礼金"),
	  FIRST_DEPOSIT_CONS("FIRST_DEPOSIT_CONS", "首存优惠"), 
	  TRANSFER_REDCOUPONS_TTGIN("TRANSFER_REDcOUPONS_TTGIN", "红包优惠-->TTG)"),
	  TRANSFER_REDCOUPONS_DTIN("TRANSFER_REDCOUPONS_DTIN", "红包优惠-->DT)"),
	  TRANSFER_REDCOUPONS_NTIN("TRANSFER_REDCOUPONS_NTIN", "红包优惠-->NT)"),
	  TRANSFER_REDCOUPONS_QTIN("TRANSFER_REDCOUPONS_QTIN", "红包优惠-->QT)"),
	TRANSFER_BIRTHDAY("TRANSFER_BIRTHDAY", "(生日礼金)额度转入(QIANYI->TTG/PT/NT/QT/DT/MG/PNG)"),
	TRANSFER_REDCOUPONS_NEWPT("TRANSFER_REDCOUPONS_NEWPT", "红包优惠-->NEWPT)"),
	  TRANSFER_REDCOUPONS_MGIN("TRANSFER_REDCOUPONS_MGIN", "红包优惠-->MG)"),
	TRANSFER_HB("TRANSFER_HB", "(自助红包奖金)额度转入(longdu->TTG/PT/NT/QT/MG/DT)"),
	  XIMA_CONS("XIMA_CONS", "洗码优惠"), 
	  BANK_TRANSFER_CONS("BANK_TRANSFER_CONS", "转账优惠"),
	  OFFER_CONS("OFFER_CONS", "再存优惠"),
	  WEEKSENT("WEEKSENT", "周周回馈优惠"),
	  PROFIT("PROFIT", "负盈利反赠优惠"),
	  YAOYAOLE("YAOYAOLE", "摇摇乐"),
	  TRANSFER_IN("TRANSFER_IN", "额度转入(LONGDU->EA)"),
	  TRANSFER_OUT("TRANSFER_OUT", "额度转出(EA->LONGDU)"), 
	  TRANSFER_DSPIN("TRANSFER_DSPIN", "额度转入(LONGDU->AG)"),
	  TRANSFER_EMIGRATED("TRANSFER_EMIGRATED", "(全民闯关奖金)额度转入(齐乐->TTG/PT/NT/QT)"),
	  TRANSFER_DSPOUT("TRANSFER_DSPOUT", "额度转出(AG->LONGDU)"), 
	  TRANSFER_DSPAGININ("TRANSFER_DSPAGININ", "额度转入(LONGDU->AGIN)"),
	  TRANSFER_DSPAGINOUT("TRANSFER_DSPAGINOUT", "额度转出(AGIN->LONGDU)"),
	  TRANSFER_KENOOUT("TRANSFER_KENOOUT", "额度转出(KENO->LONGDU)"), 
	  TRANSFER_KENOIN("TRANSFER_KENOIN", "额度转入(LONGDU->KENO)"),
	  TRANSFER_KENO2OUT("TRANSFER_KENO2OUT", "额度转出(KENO2->LONGDU)"), 
	  TRANSFER_KENO2IN("TRANSFER_KENO2IN", "额度转入(LONGDU->KENO2)"),
	  TRANSFER_BBINOUT("TRANSFER_BBINOUT", "额度转出(BBIN->LONGDU)"),
	  TRANSFER_BBININ("TRANSFER_BBININ", "额度转入(LONGDU->BBIN)"),
	  TRANSFER_NEWPTOUT("TRANSFER_NEWPTOUT", "额度转出(NEWPT->LONGDU)"),
	  TRANSFER_MEWPTIN("TRANSFER_MEWPTIN", "额度转入(LONGDU->NEWPT)"),
	  TRANSFER_SLOTIN("TRANSFER_SLOTIN", "额度转入(LONGDU->SLOT)"),
	  TRANSFER_SLOTOUT("TRANSFER_SLOTOUT", "额度转入(SLOT->LONGDU)"),
	  TRANSFER_PTIN("TRANSFER_PTIN", "额度转入(LONGDU->PT)"),
	  TRANSFER_PTOUT("TRANSFER_PTOUT", "额度转入(PT->LONGDU)"),
	  TRANSFER_SBOUT("TRANSFER_SBOUT", "额度转出(SB->LONGDU)"),
	  TRANSFER_DTIN("TRANSFER_DTIN", "额度转入(LONGDU->DT)"),
	  TRANSFER_DTOUT("TRANSFER_DTGOUT", "额度转出(DT->LONGDU)"),
	  TRANSFER_SBIN("TRANSFER_SBIN", "额度转入(LONGDU->SB)"),
	  TRANSFER_BOKIN("TRANSFER_BOKIN", "额度转入(LONGDU->BOK)"),
	  TRANSFER_BOKOUT("TRANSFER_BOKOUT", "额度转出(BOK->LONGDU)"),
	  TRANSFER_SIXLOTTERYOUT("TRANSFER_SIXLOTTERYOUT", "额度转出(SIXLOTTERY->LONGDU)"), 
	  TRANSFER_SIXLOTTERYIN("TRANSFER_SIXLOTTERYIN", "额度转入(LONGDU->SIXLOTTERY)"),
	  TRANSFER_TTGIN("TRANSFER_TTGIN", "额度转入(LONGDU->TTG)"),
	  TRANSFER_TTGOUT("TRANSFER_TTGOUT", "额度转出(TTG->LONGDU)"),  
	  TRANSFER_QTIN("TRANSFER_QTIN", "额度转入(LONGDU->QT)"),
	  TRANSFER_QTOUT("TRANSFER_QTOUT", "额度转出(QT->LONGDU)"),
	  TRANSFER_NTIN("TRANSFER_NTIN", "额度转入(LONGDU->NT)"),
	  TRANSFER_NTOUT("TRANSFER_NTOUT", "额度转出(NT->LONGDU)"),
	  TRANSFER_MGIN("TRANSFER_MGIN", "额度转入(LONGDU->MG)"),
	  TRANSFER_MGOUT("TRANSFER_MGOUT", "额度转入(MG->LONGDU)"),
	  TRANSFER_SBAOUT("TRANSFER_SBAOUT", "额度转出(SBA->LONGDU)"),
	  TRANSFER_SBAIN("TRANSFER_SBAIN", "额度转入(LONGDU->SBA)"),
	  TRANSFER_EBETIN("TRANSFER_EBETIN", "额度转入(LONGDU->EBET)"),
	  TRANSFER_EBETOUT("TRANSFER_EBETOUT", "额度转出(EBET->LONGDU)"),
	  
	  TRANSFER_JCIN("TRANSFER_JCIN", "额度转入(LONGDU->JC)"),
	  TRANSFER_JCOUT("TRANSFER_JCOUT", "额度转出(JC->LONGDU)"),
	  
	  TRANSFER_GPIIN("TRANSFER_GPIIN", "额度转入(LONGDU->GPI)"),
	  TRANSFER_GPIOUT("TRANSFER_GPIOUT", "额度转出(GPI->LONGDU)"),
	  
	  TRANSFER_N2LIVE_IN("TRANSFER_N2LIVEIN", "额度转入(LONGDU->N2Live)"),
	  TRANSFER_N2LIVE_OUT("TRANSFER_N2LIVEOUT", "额度转出(N2Live->LONGDU)"),

	  TRANSFER_EBETAPPIN("TRANSFER_EBETAPPIN", "额度转入(LONGDU->EBETAPP)"),
	  TRANSFER_EBETAPPOUT("TRANSFER_EBETAPPOUT", "额度转出(EBETAPP->LONGDU)"),

	  CHANGE_MANUAL("CHANGE_MANUAL", "手工增减额度"), 
	  TRANSFER_FRIEND_COUPON("TRANSFER_FRIEND_COUPON", "(推荐好友奖金)额度转入(LONGDU->TTG/PT/NT/QT)"),
	  TRANSFER_QD_COUPON("TRANSFER_QD_COUPON", "(签到奖金)额度转入(LONGDU->TTG/PT/NT/QT)"),
//	  ADD_FOR_TEST("ADD_FOR_TEST", "试玩账户添加额度"),
//	  COMMISSION("COMMISSION","合作伙伴佣金"),
//	  CHANGE_MATCH("CHANGE_MATCH","参加擂台赛添加初始额度"),
	  ADD_OFFER("ADD_OFFER","再存优惠"),
	  COMMISSION("COMMISSION","代理佣金"),
	  TRANSFER_IN_COUPON("TRANSFER_IN_COUPON", "(优惠劵)额度转入(LONGDU->EA)"),
	  TRANSFER_DSPIN_COUPON("TRANSFER_DSPIN_COUPON", "(优惠劵)额度转入(LONGDU->AG)"),
	  TRANSFER_BBININ_COUPON("TRANSFER_BBININ_COUPON", "(优惠劵)额度转入(LONGDU->BBIN)"),
	  TRANSFER_KENOIN_COUPON("TRANSFER_KENOIN_COUPON", "(优惠劵)额度转入(LONGDU->KENO)"),
	  TRANSFER_DSPAGIN_COUPON("TRANSFER_DSPAGIN_COUPON", "(优惠劵)额度转入(LONGDU->AGIN)"),
	  TRANSFER_PT_COUPON("TRANSFER_PT_COUPON", "(优惠劵)额度转入(LONGDU->PT)"),
	  TRANSFER_NEWPT_COUPON("TRANSFER_NEWPT_COUPON", "(优惠劵)额度转入(LONGDU->NEWPT)"),
	  TRANSFER_POINT_INT("TRANSFER_POINT_INT", "积分兑换奖金"),
	  TRANSFER_SB_COUPON("TRANSFER_SB_COUPON", "(优惠劵)额度转入(LONGDU->SB)"),
	  
	  TRANSFER_LONGDUIN("TRANSFER_LONGDUIN","(代理账户)额度转入(AGENT->LONGDU)"),
	  TRANSFER_AGENTOUT("TRANSFER_AGENTOUT","(代理账户)老虎机额度转出(AGENT->LONGDU)"),

	  BIRTHDAY("BIRTHDAY", "生日礼金"),
	  TRANSFER_PNGIN("TRANSFER_PNGIN", "额度转入(LONGDU->PNG)"),
	  TRANSFER_PNGOUT("TRANSFER_PNGOUT", "额度转出(PNG->LONGDU)"),
	  TRANSFER_REDRAINOUT("TRANSFER_REDRAINOUT", "额度转出(dy->红包雨账户)"),
	  TRANSFER_REDRAIN_OUT("TRANSFER_REDRAIN_OUT", "(红包雨)额度转入(TTG/PT/NT/QT/MG/DT/PNG)");

		public static String getText(String code) {
		    CreditChangeType[] p = values();
		    for (int i = 0; i < p.length; ++i) {
		      CreditChangeType type = p[i];
		      if (type.getCode().equals(code))
		        return type.getText();
		    }
		    return null;
		  }
		private String code;
	
		private String text;
	
	  private CreditChangeType(String code, String text) {
		this.code = code;
		this.text = text;
	}
	
	  public String getCode()
	  {
	    return this.code;
	  }
	
	  public String getText() {
	    return this.text;
	  }

}
