package dfh.model.enums;

/**
 * 额度变化类型
 * 
 *
 */
public enum CreditChangeType
{
	  NETPAY("NETPAY", "在线支付"),
	  NETPAYHL("NETPAYHL", "户内转账调单"),
	  REPAIR_PAYORDER("REPAIR_PAYORDER", "支付补单"),
	  CASHIN("CASHIN", "存款"), 
	  PROXYADVANCE("PROXYADVANCE", "代理信用预支"),
	  CASHOUT("CASHOUT", "提款"),
	  CASHOUT_RETURN("CASHOUT_RETURN", "退还提款"),
	  REBANKINFO("REBANKINFO", "银改"),
	  PRIZE("PRIZE", "幸运抽奖"),
	  BIRTHDAY("BIRTHDAY", "生日礼金"),
	  ACTIVITY442("活动礼金" , "活动礼金"),
	TRANSFER_REDRAINOUT("TRANSFER_REDRAINOUT", "额度转出(龙都->红包雨账户)"),
	TRANSFER_REDRAIN_OUT("TRANSFER_REDRAIN_OUT", "(红包雨)额度转入(TTG/PT/NT/QT/MG/DT/PNG)"),
	  	TRANSFER_REDCOUPONS_NEWPT("TRANSFER_REDCOUPONS_NEWPT", "红包优惠券-->NEWPT)"),
	  	TRANSFER_REDCOUPONS_MGIN("TRANSFER_REDCOUPONS_MGIN", "红包优惠券-->MG)"),
		TRANSFER_REDCOUPONS_DTIN("TRANSFER_REDCOUPONS_DTIN", "红包优惠券-->DT)"),
		TRANSFER_REDCOUPONS_QTIN("TRANSFER_REDCOUPONS_QTIN", "红包优惠券-->QT)"),
		TRANSFER_REDCOUPONS_NTIN("TRANSFER_REDCOUPONS_NTIN", "红包优惠券-->NT)"),
		TRANSFER_REDCOUPONS_TTGIN("TRANSFER_REDCOUPONS_TTGIN", "红包优惠券-->TTG)"),
		TRANSFER_REDCOUPONS_PNGIN("TRANSFER_REDCOUPONS_PNGIN", "红包优惠券-->PNG)"),
		TRANSFER_REDCOUPONS_AGIN("TRANSFER_REDCOUPONS_AGIN", "红包优惠券-->AGIN)"),
		TRANSFER_REDCOUPONS_SLOT("TRANSFER_REDCOUPONS_SLOT", "红包优惠券-->SLOT)"),
		TRANSFER_NEWPT_COUPON("TRANSFER_NEWPT_COUPON", "存送优惠劵-->NEWPT)"),
		TRANSFER_MG_COUPON("TRANSFER_MG_COUPON", "存送优惠劵-->MG)"),
		TRANSFER_DT_COUPON("TRANSFER_DT_COUPON", "存送优惠劵-->DT)"),
		TRANSFER_QT_COUPON("TRANSFER_QT_COUPON", "存送优惠劵-->QT)"),
		TRANSFER_NT_COUPON("TRANSFER_NT_COUPON", "存送优惠劵-->NT)"),
		TRANSFER_TTG_COUPON("TRANSFER_TTG_COUPON", "存送优惠劵-->TTG)"),
		TRANSFER_PNG_COUPON("TRANSFER_PNG_COUPON", "存送优惠劵-->PNG)"),
		TRANSFER_AGIN_COUPON("TRANSFER_AGIN_COUPON", "存送优惠劵-->AGIN)"),
		TRANSFER_SLOT_COUPON("TRANSFER_SLOT_COUPON", "存送优惠劵-->SLOT)"),
	  LEVELPRIZE("LEVELPRIZE", "晋级礼金"),
	  WEEKSENT("WEEKSENT", "周周回馈优惠"),
	  PROFIT("PROFIT", "负盈利反赠优惠"),
	  YAOYAOLE("YAOYAOLE", "摇摇乐礼金"),
	  FIRST_DEPOSIT_CONS("FIRST_DEPOSIT_CONS", "首存优惠"), 
	  XIMA_CONS("XIMA_CONS", "洗码优惠"), 
	  BANK_TRANSFER_CONS("BANK_TRANSFER_CONS", "转账优惠"),
	  OFFER_CONS("OFFER_CONS", "再存优惠"),
	  TRANSFER_CHESSIN("TRANSFER_CHESSIN", "额度转入(LONGDU->761)"),
	  TRANSFER_CHESSOUT("TRANSFER_CHESSOUT", "额度转出(761->LONGDU)"),
	  TRANSFER_IN("TRANSFER_IN", "额度转入(LONGDU->EA)"),
	  TRANSFER_OUT("TRANSFER_OUT", "额度转出(EA->LONGDU)"),
	  TRANSFER_DSPIN("TRANSFER_DSPIN", "额度转入(LONGDU->AG)"),
	  TRANSFER_DSPOUT("TRANSFER_DSPOUT", "额度转出(AG->LONGDU)"),
	  TRANSFER_DSPAGININ("TRANSFER_DSPAGININ", "额度转入(LONGDU->AGIN)"),
	  TRANSFER_DSPAGINOUT("TRANSFER_DSPAGINOUT", "额度转出(AGIN->LONGDU)"),
	TRANSFER_PBOUT("TRANSFER_PBOUT", "额度转出(PB->LONGDU)"),
	TRANSFER_PBIN("TRANSFER_PBIN", "额度转入(LONGDU->PB)"),
	  TRANSFER_BBININ("TRANSFER_BBININ", "额度转入(LONGDU->BBIN)"),
	  TRANSFER_BBINOUT("TRANSFER_BBINOUT", "额度转出(BBIN->LONGDU)"),
	TRANSFER_FANYAOUT("TRANSFER_FANYAOUT", "额度转出(FANYA->LONGDU)"),
	TRANSFER_FANYAIN("TRANSFER_FANYAIN", "额度转入(LONGDU->FANYA)"),
	  TRANSFER_NEWPTOUT("TRANSFER_NEWPTOUT", "额度转出(NEWPT->LONGDU)"),
	  TRANSFER_MEWPTIN("TRANSFER_MEWPTIN", "额度转入(LONGDU->NEWPT)"),
	  TRANSFER_SLOTTIN("TRANSFER_SLOTIN", "额度转入(LONGDU->SLOT)"),
	  TRANSFER_SLOTOUT("TRANSFER_SLOTOUT", "额度转出(SLOT->LONGDU)"),
	  TRANSFER_SBOUT("TRANSFER_SBOUT", "额度转出(SB->LONGDU)"),
	  TRANSFER_SBIN("TRANSFER_SBIN", "额度转入(LONGDU->SB)"),
	TRANSFER_KYQPIN("TRANSFER_KYQPIN", "额度转入(LONGDU->开元棋牌)"),
	TRANSFER_KYQPOUT("TRANSFER_KYQPOUT", "额度转出(开元棋牌->LONGDU)"),
	TRANSFER_VRIN("TRANSFER_VRIN", "额度转入(LONGDU->VR彩票)"),
	TRANSFER_VROUT("TRANSFER_VROUT", "额度转出(VR彩票->LONGDU)"),
	  TRANSFER_KENOIN("TRANSFER_KENOIN", "额度转入(LONGDU->KENO)"),
	  TRANSFER_KENOOUT("TRANSFER_KENOOUT", "额度转出(KENO->LONGDU)"),
	  TRANSFER_KENO2OUT("TRANSFER_KENO2OUT", "额度转出(KENO2->LONGDU)"), 
	  TRANSFER_KENO2IN("TRANSFER_KENO2IN", "额度转入(LONGDU->KENO2)"),
	 
	  TRANSFER_PTIN("TRANSFER_PTIN", "额度转入(LONGDU->PT)"),
	  TRANSFER_PTOUT("TRANSFER_PTOUT", "额度转出(PT->LONGDU)"),
	  EMIGRATED391("EMIGRATED391", "全民闯关奖励转入游戏"),
	  TRANSFER_SIXLOTTERYOUT("TRANSFER_SIXLOTTERYOUT", "额度转出(SIXLOTTERY->LONGDU)"), 
	  TRANSFER_SIXLOTTERYIN("TRANSFER_SIXLOTTERYIN", "额度转入(LONGDU->SIXLOTTERY)"),
	  TRANSFER_FRIEND_COUPON("TRANSFER_FRIEND_COUPON", "(推荐好友奖金)额度转入(LONGDU->TTG/PT/NT/QT)"),
	  
	  TRANSFER_EBETIN("TRANSFER_EBETIN", "额度转入(LONGDU->EBET)"),
	  TRANSFER_EBETOUT("TRANSFER_EBETOUT", "额度转出(EBET->LONGDU)"),
	  
	  TRANSFER_JCIN("TRANSFER_JCIN", "额度转入(LONGDU->SSC)"),
	  TRANSFER_JCOUT("TRANSFER_JCOUT", "额度转出(SSC->LONGDU)"),
	  
	  TRANSFER_DTIN("TRANSFER_DTIN", "额度转入(LONGDU->DT)"),
	  TRANSFER_DTOUT("TRANSFER_DTGOUT", "额度转出(DT->LONGDU)"),
	  
	  TRANSFER_NTIN("TRANSFER_NTIN", "额度转入(LONGDU->NT)"),
	  TRANSFER_NTOUT("TRANSFER_NTOUT", "额度转出(NT->LONGDU)"),
	  
	  TRANSFER_GPIIN("TRANSFER_GPIIN", "额度转入(LONGDU->GPI)"),
	  TRANSFER_GPIOUT("TRANSFER_GPIOUT", "额度转出(GPI->LONGDU)"),
	  
	  TRANSFER_TTGIN("TRANSFER_TTGIN", "额度转入(LONGDU-TTG)"),
	  TRANSFER_TTGOUT("TRANSFER_TTGOUT", "额度转出(TTG->LONGDU)"),
	  
	  TRANSFER_QTIN("TRANSFER_QTIN", "额度转入(LONGDU->QT)"),
	  TRANSFER_QTOUT("TRANSFER_QTOUT", "额度转出(QT->LONGDU)"),
	  
	  TRANSFER_MGIN("TRANSFER_MGIN", "额度转入(LONGDU->MG)"),
	  TRANSFER_MGOUT("TRANSFER_MGOUT", "额度转入(MG->LONGDU)"),

	  TRANSFER_FISHOUT("TRANSFER_FISHOUT", "额度转出(HYG捕鱼->LONGDU)"),
	  TRANSFER_FISHIN("TRANSFER_FISHIN", "额度转入(LONGDU->HYG捕鱼)"),

	  TRANSFER_EBETAPPIN("TRANSFER_EBETAPPIN", "额度转入(LONGDU->EBETAPP)"),
	  TRANSFER_EBETAPPOUT("TRANSFER_EBETAPPOUT", "额度转出(EBETAPP->LONGDU)"),

	  TRANSFER_N2LIVE_IN("TRANSFER_N2LIVEIN", "额度转入(LONGDU->N2Live)"),
	  TRANSFER_N2LIVE_OUT("TRANSFER_N2LIVEOUT", "额度转出(N2Live->LONGDU)"),
	  
	  CHANGE_MANUAL("CHANGE_MANUAL", "手工增减额度"),
	  
	  CHANGE_QUOTAL("CHANGE_QUOTAL", "增减额度"),
	  CHANGE_QUOTALSLOT("CHANGE_QUOTALSLOT", "增减额度(代理老虎机佣金)"),
	  CHANGE_COMMISSIONSDAY("CHANGE_COMMISSIONSDAY", "日结佣金"),
	  TRANSFER_POINT_INT("TRANSFER_POINT_INT", "积分兑换奖金"),
	  TRANSFER_QD_COUPON("TRANSFER_QD_COUPON", "(签到奖金)额度转入(LONGDU->TTG/PT)"),


	  CHANGE_BANKMANUAL("CHANGE_BANKMANUAL", "手工增减银行额度"),
	  CHANGE_CROSSPLATFORM("CHANGE_CROSSPLATFORM", "跨平台转账"),
	  CHANGE_QUOTAPROBLEM("CHANGE_QUOTAPROBLEM", "后台额度问题"),
	  CHANGE_ARBITRAGE("CHANGE_ARBITRAGE", "套汇"),
//	  ADD_FOR_TEST("ADD_FOR_TEST", "试玩账户添加额度"),
//	  COMMISSION("COMMISSION","合作伙伴佣金"),
//	  CHANGE_MATCH("CHANGE_MATCH","参加擂台赛添加初始额度"),
	  ADD_OFFER("ADD_OFFER","再存优惠"),
	  COMMISSION("COMMISSION","代理佣金"),
	TRANSFER_HB("TRANSFER_HB","存款红包"),
	  TRANSFER_IN_COUPON("TRANSFER_IN_COUPON", "(优惠劵)额度转入(LONGDU->EA)"),
	  TRANSFER_DSPIN_COUPON("TRANSFER_DSPIN_COUPON", "(优惠劵)额度转入(LONGDU->AG)"),
	  TRANSFER_DSPAGIN_COUPON("TRANSFER_DSPAGIN_COUPON", "(优惠劵)额度转入(LONGDU->AGIN)"),
	  TRANSFER_BBININ_COUPON("TRANSFER_BBININ_COUPON", "(优惠劵)额度转入(LONGDU->BBIN)"),
	  TRANSFER_KENOIN_COUPON("TRANSFER_KENOIN_COUPON", "(优惠劵)额度转入(LONGDU->KENO)"),
	  TRANSFER_PT_COUPON("TRANSFER_PT_COUPON", "(优惠劵)额度转入(LONGDU->PT)"),
	  TRANSFER_SB_COUPON("TRANSFER_SB_COUPON", "(优惠劵)额度转入(LONGDU->SB)"),
	  
	  TRANSFER_PNGIN("TRANSFER_PNGIN", "额度转入(LONGDU->PNG)"),
	  TRANSFER_PNGOUT("TRANSFER_PNGOUT", "额度转出(PNG->LONGDU)"),
	  TRANSFER_SBAOUT("TRANSFER_SBAOUT", "额度转出(SBA->LONGDU)"),
	  TRANSFER_SBAIN("TRANSFER_SBAIN", "额度转入(LONGDU->SBA)"),
	  TRANSFER_MWGOUT("TRANSFER_MWGOUT", "额度转出(MWG->LONGDU)"),
	  TRANSFER_MWGIN("TRANSFER_MWGIN", "额度转入(LONGDU->MWG)"),	
	  TRANSFER_AGININ("TRANSFER_AGININ", "额度转入(LONGDU->AGIN)"),
	  TRANSFER_AGINOUT("TRANSFER_AGINOUT", "额度转出(AGIN->LONGDU)"),
	  TRANSFER_LONGDUIN("TRANSFER_LONGDUIN","(代理账户)额度转入(AGENT->LONGDU)"),
	  TRANSFER_AGENTOUT("TRANSFER_AGENTOUT","(代理账户)老虎机额度转出(AGENT->LONGDU)"),
	  TRANSFER_BITOUT("TRANSFER_BITOUT", "额度转出(BIT->LONGDU)"),
	  TRANSFER_BITIN("TRANSFER_BITIN", "额度转入(LONGDU->BIT)");
	  
		public static String getText(String code) {
		    CreditChangeType[] p = values();
		    for (int i = 0; i < p.length; ++i) {
		      CreditChangeType type = p[i];
		      if (type.getCode().equals(code))
		        return type.getText();
		    }
		    return null;
		  }
		
		public static String getCode(String code) {
			CreditChangeType[] p = values();
			for (int i = 0; i < p.length; ++i) {
				CreditChangeType type = p[i];
				if (type.getCode().equals(code))
					return type.getCode();
			}
			return null;
		}
		
		private String code;
	
		private String text;
	
	  private CreditChangeType(String code, String text) {
		this.code = code;
		this.text = text;
	}
	
	  public String getCode()
	  {
	    return this.code;
	  }
	
	  public String getText() {
	    return this.text;
	  }

}
