package com.nnti.common.constants;

public interface CreditChangeType {

	// 额度转入(PT)
	String TRANSFER_PT_IN = "TRANSFER_MEWPTIN";
	// 额度转出(PT)
	String TRANSFER_PT_OUT = "TRANSFER_NEWPTOUT";
	// 额度转入(DT)
	String TRANSFER_DT_IN = "TRANSFER_DTIN";
	// 额度转出(DT)
	String TRANSFER_DT_OUT = "TRANSFER_DTGOUT";
	// 额度转入(MG)
	String TRANSFER_MG_IN = "TRANSFER_MGIN";
	// 额度转出(MG)
	String TRANSFER_MG_OUT = "TRANSFER_MGOUT";
	// 额度转入(CQ9)
	String TRANSFER_CQ9_IN = "TRANSFER_CQ9IN";
	// 额度转入(PG)
	String TRANSFER_PG_IN = "TRANSFER_PGIN";
	// 额度转出(CQ9)
	String TRANSFER_CQ9_OUT = "TRANSFER_CQ9OUT";
	// 额度转出(PG)
	String TRANSFER_PG_OUT = "TRANSFER_PGOUT";
	// 额度转入(SW)
	String TRANSFER_SW_IN = "TRANSFER_SWIN";
	// 额度转出(SW)
	String TRANSFER_SW_OUT = "TRANSFER_SWOUT";
	// 额度转入(NT)
	String TRANSFER_NT_IN = "TRANSFER_NTIN";
	// 额度转出(NT)
	String TRANSFER_NT_OUT = "TRANSFER_NTOUT";
	// 额度转入(QT)
	String TRANSFER_QT_IN = "TRANSFER_QTIN";
	// 额度转出(QT)
	String TRANSFER_QT_OUT = "TRANSFER_QTOUT";
	// 额度转入(TTG)
	String TRANSFER_TTG_IN = "TRANSFER_TTGIN";
	// 额度转出(TTG)
	String TRANSFER_TTG_OUT = "TRANSFER_TTGOUT";
	// 额度转入(PNG)
	String TRANSFER_PNG_IN = "TRANSFER_PNGIN";
	// 额度转出(PNG)
	String TRANSFER_PNG_OUT = "TRANSFER_PNGOUT";
	// 额度转入(N2)
	String TRANSFER_N2LIVE_IN = "TRANSFER_N2LIVEIN";
	// 额度转出(N2)
	String TRANSFER_N2LIVE_OUT = "TRANSFER_N2LIVEOUT";
	// 额度转入(AGIN)
	String TRANSFER_AGIN_IN = "TRANSFER_AGININ";
	// 额度转出(AGIN)
	String TRANSFER_AGIN_OUT = "TRANSFER_AGINOUT";
	// 额度转入(SBA)
	String TRANSFER_SBA_IN = "TRANSFER_SBAIN";
	// 额度转出(SBA)
	String TRANSFER_SBA_OUT = "TRANSFER_SBAOUT";
	// 额度转入(MWG)
	String TRANSFER_MWG_IN = "TRANSFER_MWGIN";
	// 额度转出(MWG)
	String TRANSFER_MWG_OUT = "TRANSFER_MWGOUT";
	// 额度转入(OG)
	String TRANSFER_OG_IN = "TRANSFER_OGIN";
	// 额度转出(MWG)
	String TRANSFER_OG_OUT = "TRANSFER_OGOUT";
	// 额度转入(EA)
	String TRANSFER_IN = "TRANSFER_IN";
	// 额度转出(EA)
	String TRANSFER_OUT = "TRANSFER_OUT";
	// 额度转入(EBETAPP)
	String TRANSFER_EBETAPP_IN = "TRANSFER_EBETAPPIN";
	// 额度转出(EBETAPP)
	String TRANSFER_EBETAPP_OUT = "TRANSFER_EBETAPPOUT";
	// 额度转入(SLOT)
	String TRANSFER_SLOT_IN = "TRANSFER_SLOTIN";
	// 额度转出(SLOT)
	String TRANSFER_SLOT_OUT = "TRANSFER_SLOTOUT";
	// 额度转入(CHESS)
	String TRANSFER_CHESS_IN = "TRANSFER_CHESSIN";
	// 额度转出(CHESS)
	String TRANSFER_CHESS_OUT = "TRANSFER_CHESSOUT";
	// 额度转入(BBIN)
	String TRANSFER_BBIN_IN = "TRANSFER_BBININ";
	// 额度转出(BBIN)
	String TRANSFER_BBIN_OUT = "TRANSFER_BBINOUT";
	// 红包优惠券(PT)
	String TRANSFER_REDCOUPONS_NEWPT = "TRANSFER_REDCOUPONS_NEWPT";
	// 红包优惠券(MG)
	String TRANSFER_REDCOUPONS_MGIN = "TRANSFER_REDCOUPONS_MGIN";
	// 红包优惠券(CQ9)
	String TRANSFER_REDCOUPONS_CQ9IN = "TRANSFER_REDCOUPONS_CQ9IN";
	// 红包优惠券(PG)
	String TRANSFER_REDCOUPONS_PGIN = "TRANSFER_REDCOUPONS_PGIN";
	// 红包优惠券(SW)
	String TRANSFER_REDCOUPONS_SWIN = "TRANSFER_REDCOUPONS_SWIN";
	// 红包优惠券(DT)
	String TRANSFER_REDCOUPONS_DTIN = "TRANSFER_REDCOUPONS_DTIN";
	// 红包优惠券(QT)
	String TRANSFER_REDCOUPONS_QTIN = "TRANSFER_REDCOUPONS_QTIN";
	// 红包优惠券(NT)
	String TRANSFER_REDCOUPONS_NTIN = "TRANSFER_REDCOUPONS_NTIN";
	// 红包优惠券(TTG)
	String TRANSFER_REDCOUPONS_TTGIN = "TRANSFER_REDCOUPONS_TTGIN";
	// 红包优惠券(PNG)
	String TRANSFER_REDCOUPONS_PNGIN = "TRANSFER_REDCOUPONS_PNGIN";
	// 红包优惠券(AGIN)
	String TRANSFER_REDCOUPONS_AGIN = "TRANSFER_REDCOUPONS_AGIN";
	// 红包优惠券(SLOT)
	String TRANSFER_REDCOUPONS_SLOT = "TRANSFER_REDCOUPONS_SLOT";
	// 存送优惠券(PT)
	String TRANSFER_NEWPT_COUPON = "TRANSFER_NEWPT_COUPON";
	// 存送优惠券(MG)
	String TRANSFER_MG_COUPON = "TRANSFER_MG_COUPON";
	// 存送优惠券(CQ9)
	String TRANSFER_CQ9_COUPON = "TRANSFER_CQ9_COUPON";
	// 存送优惠券(CQ9)
	String TRANSFER_PG_COUPON = "TRANSFER_PG_COUPON";
	// 存送优惠券(SW)
	String TRANSFER_SW_COUPON = "TRANSFER_SW_COUPON";
	// 存送优惠券(DT)
	String TRANSFER_DT_COUPON = "TRANSFER_DT_COUPON";
	// 存送优惠券(QT)
	String TRANSFER_QT_COUPON = "TRANSFER_QT_COUPON";
	// 存送优惠券(NT)
	String TRANSFER_NT_COUPON = "TRANSFER_NT_COUPON";
	// 存送优惠券(TTG)
	String TRANSFER_TTG_COUPON = "TRANSFER_TTG_COUPON";
	// 存送优惠券(PNG)
	String TRANSFER_PNG_COUPON = "TRANSFER_PNG_COUPON";
	// 存送优惠券(AGIN)
	String TRANSFER_AGIN_COUPON = "TRANSFER_AGIN_COUPON";
	// 存送优惠券(SLOT)
	String TRANSFER_SLOT_COUPON = "TRANSFER_SLOT_COUPON";
	// 红包雨(主账户)
	String TRANSFER_SELF_IN = "TRANSFER_SELFIN";
	//
	String CASHOUT = "CASHOUT";
}